# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-11 15:16
from __future__ import unicode_literals

from django.db import migrations, models


def make_data(apps, schema_editor):
    MyModel = apps.get_model("concurrency", "MyModel")
    db_alias = schema_editor.connection.alias
    MyModel.objects.using(db_alias).create(my_field='abc123')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_field', models.CharField(max_length=10)),
            ],
        ),
        migrations.RunPython(make_data)  # doesn't matter
    ]
